### ISSUE TITLE
Simplest possible implementation

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Monitor#1]
I love a one-issue coding project. Let's extract a Twinkles light curve, Bryce!
- [x] Write `LightCurve` class #7 
- [ ] Get test dataset #4 
- [ ] Compute light curve quality #9

**Comment by rbiswas4** [comment]
@jbkalmbach @drphilmarshall 
I suppose you are doing this from a database of images ?  Or is this from a database of DM results?
As this is a simulation comparison project, would it be interesting to also have these from the sim instance catalogs for comparison? I have bits of code generating light curves from simulated instance catalogs as examples in  
https://github.com/lsst/sims_catUtils/blob/master/examples/SNCatalog_example.ipynb
But putting them together in a sensible, organized manner (like the monitor) would be helpful for many purposes. Or would this qualify as a second issue?

**Comment by drphilmarshall** [comment]
@rbiswas4 Good idea to ask the Monitor to look up the reference light curve too. I think this deserves a separate issue though, as it goes beyond the Simplest Possible Implementation. At this point I guess we are starting from a "database" of DM results - I don't know what format they are in right now but I guess Bryce will figure it out! It'll be good to have the Monitor be able to cope with a variety of input formats, starting with the one the Twinkles ForcedSources are currently in.

**Comment by drphilmarshall** [comment]
Alright @jbkalmbach this issue is now an epic. see above for checkboxes.

I guess all these need doing this coming week, so we can run The Monitor on the Twinkles DM Level 2 ForcedSource catalog(s)! LMK if you want to pair-code by hangout, Wednesday afternoon could be a good time.
