### ISSUE TITLE
Load Monitor input from database

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Monitor#23]
- [x] Set up SQL database at UW #20 
- [x] Update Monitor code to interact with database #24

**Comment by rbiswas4** [comment]
More specifically, I think Update Monitor code would be good to achieve by having multiple class methods, including the old one which tries to build the files from a data repository. But a new class method should interact with the database. 

The thing we should all think about is what inputs we would like to provide:
- [ ] objectId
- [ ] ra, dec coordinates, 
- [ ] ra, dec coordinates, nearest match
- [ ] brightness/ other properties ?

Which observations to pull up:
- [ ] SNR threshold ?
- [ ] Given a set of visits?
- [ ] MJD and max MJD ?

**Comment by jbkalmbach** [comment]
Also, leaving note here to watch DarkEnergyScienceCollaboration/Twinkles#191 to update needs of this epic as they change.

**Comment by jbkalmbach** [comment]
Both of the issues in the checklist have actually been closed already.
