### ISSUE TITLE
Comparison with reference light curves

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Monitor#3]
- [ ] Identify PhoSim Catalog entry for each forced photometry #21
- [ ] Organize PhoSim Catalog information (including object metadata) into light curve #22 
- [ ] 3rd party operation, leading to light curve plots #29

Here's a good idea from @rbiswas4 , reproduced from #1:

> I have bits of code generating light curves from simulated instance catalogs as examples in https://github.com/lsst/sims_catUtils/blob/master/examples/SNCatalog_example.ipynb but putting them together in a sensible, organized manner (like the monitor) would be helpful for many purposes.

Thanks Rahul!

**Comment by drphilmarshall** [comment]
Ah - we didn't mention the reference part of the tiny dataset in #4 but I guess we'd want to add that later to help development of the reference part of the `LightCurve` class.

**Comment by drphilmarshall** [comment]
I think we want a `Monitor.get_objid(ra,dec)` method, don't you, Rahul?

This functionality is needed by the hypothetical notebook referred to in this https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/142#issuecomment-192027177

**Comment by drphilmarshall** [comment]
Hey @jbkalmbach I just added a 3rd task to this Epic, following today's meeting: we need to store some metadata about the reference objects as well. Supernovae will have true SALT2 parameters, redshift etc. Strong lenses will have lens and source redshifts, OM10 IDs, image positions, time delays etc etc. In each case we may want to use this metadata when doing our light curve tests, and will certainly want it when looking at light curve quality over the sample. This could be a good time to start sub-classing the Monitor into an SNMonitor and an SLMonitor, if you haven't started already, perhaps? I'll leave you to issue the metadata storage coding, after you've thought a bit about the subclassing design.

**Comment by drphilmarshall** [comment]
Hi @rbiswas4 ! Can you open a PR from the `reference_lc` branch please? It looks like you could be able to close not only this issue but also #21 and #22 - please do review these issues and close them if at all possible, preferably via commit messages (so that they auto-close when we accept the PR). Thank you! Excited to see the light curve comparisons :-)

**Comment by rbiswas4** [comment]
@drphilmarshall According to the items you have listed out, it would seem that the current work does not close the issue? Anyway, I put in a PR and an example notebook which should have some of the documentation you asked for.
