### ISSUE TITLE
SLMonitor

### ISSUE THREAD

**Issue by drphilmarshall** [DarkEnergyScienceCollaboration/Monitor#30]
Hey @jbkalmbach - it looks like our strong lens capabilities are falling behind a bit. Correcting this oversight is an Epic task. What else do we need to do, apart from the following?
- [ ] #40: Use RefLightCurves code from @rbiswas4 to extract reference lensed quasar light curves
- [ ] Sub-class the Monitor into an SLMonitor that knows it needs to extract 2, 3 or 4 objects and plot/analyze them together. I know there is not much to sub-class yet - but maybe there will become more once we start trying to use the SLMonitor in anger?
- [ ] Produce demo notebook walking the user through an example, and have someone else test it

**Comment by drphilmarshall** [comment]
@jbkalmbach Feel free to make issues for each bulleted task once you are down with the program!
