### ISSUE TITLE
Measure depths of visits from 

### ISSUE THREAD

**Issue by rbiswas4** [DarkEnergyScienceCollaboration/Monitor#54]
Since we are interested in doing comparisons of truths and detected values as a function of observation parameters, we have to measure the sky noise. Let us obtain the values of five sigma depth from 
- [ ]  The Opsim  database
- [ ]  PhoSim Centroid Files and log files
- [ ] The DM analysis of the images.

The interface that we are thinking of is:
```
monitor  = Monitor()
monitor.measure_depth(*args)
# where `*args` might tell us to obtain this from the OpSim Database, and obsHistID,  or a centroid file.
```

**Comment by rbiswas4** [comment]
It appears that, unfortunately, this information is not available from the text files that phosim outputs (centroid files). which has 

```
sources numberPhotons AvgX AvgY
```

where AvgX and AvgY are pixel positions of sources.

Unless the 0s on the end are background sources, there seems to be no way of understanding the number of photons coming from background. On the other hand, many of these have `-nan` as pixel positions and 0 for the number of photons. If these are to be interpreted as backgrounds producing sky noise, is this a possibility?

**Comment by sethdigel** [comment]
Those zero-photon background sources are labeled as 'Zodiacal Light'.  I'd infer that this background must have been turned off.

Probably a rough idea of the sigma depth could come from the reported total number of photons (e.g., 7.04e11 for obshistid = 230, the first in Tom's current run, r band) and an estimate of the size of the PSF.  At least it sort of works quantitatively.  The CCDs are 800x800 arcsec.  If the effective PSF area is about 1x1", then a 5 sigma fluctuation would be about 5000 photons.  Using the table of photon counts and numbers of sources by magnitude range that phosim writes in its log file (e.g., [this one](http://srs.slac.stanford.edu/Pipeline-II/exp/LSST-DESC/log.jsp?pi=41901039)) this would correspond to something between 27th and 28th magnitude.  Seems too deep.
