### ISSUE TITLE
Simplest Possible Error Model

### ISSUE THREAD

**Issue by jbkalmbach** [DarkEnergyScienceCollaboration/Monitor#60]
- [ ] #61  Develop monitor functionality to get true fluxes from instance catalog files
- [ ] #62 Match up an object's true fluxes to observed fluxes
- [ ] #63 Develop 2-d bias map in depth, seeing space
- [ ] #64 Develop 2-d variance map in depth, seeing space
- [ ] #65 Make notebook to show bias maps and truth comparisons
- [ ] #67 Use CcdVisit Table `skyNoise` to measure depth
- [ ] #68 Have Monitor pull relevant Opsim data

The first major chunk of work in developing a working error model for Twinkles will be to develop a simple model outlined on the board pictured [here](https://github.com/DarkEnergyScienceCollaboration/Monitor/files/584719/IMG_20161110_161134488.pdf). This is broken up into a list of issues outlined above.
